# Follow this guide to publish Hydejack on Cloudflare Worker Sites: 
#
# https://workers.cloudflare.com/sites
#
# You can skip the `wrangler generate --site my-site` step, 
# as this `wranger.toml` file, and the `workers-site` directory
# have already been shipped with Hydejack. 
#
# Fill out the information below:

name = "hydejack-site"
type = "webpack"
account_id = "efb289061241436254219b424fcea4cf"
zone_id = "7ba22a65e18ec5a38434032407597e5c"
route = "https://hydejack.com/*"
workers_dev = true

[site]
bucket = "./build"
entry-point = "workers-site"
